pipeline {
    agent any
  
  stages {
        stage('Initialize') {
            steps {
                echo 'setting...'   
                 bat 'set'
            }
        }

		 stage('Testing') {
            steps {
                script {
                    try {
                        bat 'gradlew clean test --no-daemon' //run a gradle task
                    } finally {
                        junit '**/build/test-results/test/*.xml' //make the junit test results available in any case (success & failure)
                    }
                }
            }
        }
   
       } 
    post { 
        always {            
             echo 'Testing completed Successfully!'
        }
    }
}


