pipeline {
    agent any
  
  stages {
        stage('Initialize') {
            steps {
                echo 'setting...'   
                 bat 'set'
            }
        }

		 stage('Testing') {
            steps {
                script {
                    try {
                       // bat 'gradle clean test --no-daemon' 
                       echo 'tryig.....'
                      bat 'test.bat'
                    } finally {
                        junit '**/build/test-results/**.xml' 
                    }
                }
            }
        }
   
       } 
    post { 
        always {            
             echo 'Testing completed Successfully!'
        }
    }
}



